export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const CHANGE_LOADER_STATE = 'CHANGE_LOADER_STATE';
export const UPDATE_IS_AUTHORIZED = 'UPDATE_IS_AUTHORIZED';
export const LOGOUT_HANDLER = 'LOGOUT_HANDLER';